<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.List" %>
<%@ page import="com.google.appengine.api.users.User" %>
<%@ page import="com.google.appengine.api.users.UserService" %>
<%@ page import="com.google.appengine.api.users.UserServiceFactory" %>
<%@ page import="com.google.appengine.api.datastore.DatastoreServiceFactory" %>
<%@ page import="com.google.appengine.api.datastore.DatastoreService" %>
<%@ page import="com.google.appengine.api.datastore.Query" %>
<%@ page import="com.google.appengine.api.datastore.Entity" %>
<%@ page import="com.google.appengine.api.datastore.FetchOptions" %>
<%@ page import="com.google.appengine.api.datastore.Key" %>
<%@ page import="com.google.appengine.api.datastore.KeyFactory" %>
<%@ page import="guestbook.Calculator" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<%
	// Manage user inputs
	int year = Integer.parseInt(request.getParameter("year"));
	int panelGeneration = Integer.parseInt(request.getParameter("radiobutton"));
	double panelElevation = Double.parseDouble(request.getParameter("elevation"));
	double panelFacing = Double.parseDouble(request.getParameter("select"));
	double daylight = Double.parseDouble(request.getParameter("daylight"));
	double electricityCost = Double.parseDouble(request.getParameter("feedInTariff"));
	double dailyUsage = Double.parseDouble(request.getParameter("dailyUsage"));
	double feedInTariff = Double.parseDouble(request.getParameter("feedInTariff"));
	int panelAge = (int)Double.parseDouble(request.getParameter("panelAge"));
	double inverterEfficiency = Double.parseDouble(request.getParameter("inverter"));
	double shadeFactor = Double.parseDouble(request.getParameter("shade"));

	// Store basic calculations
	Calculator t = new Calculator(panelGeneration, panelElevation, panelFacing, daylight, electricityCost, dailyUsage, feedInTariff, inverterEfficiency, shadeFactor);
	double[] power = t.getLifetimeElectricityGeneration(5000);
	double[] savings = t.getLifetimeCostSavings(power);
	double[] carbonSavings = t.getLifetimeCarbonSavings(power);
	
	double[] powerYear = new double[12];
	double[] savingsYear = new double[12];
	double[] carbonsYear = new double[12];
	double[] mods = { 0.14, 0.12, 0.095, 0.07, 0.047, 0.042, 0.043, 0.047, 0.07, 0.1, 0.122, 0.146 };
	for (int i = 0; i < powerYear.length; i++) {
		powerYear[i] = mods[i] * power[year];
		savingsYear[i] = mods[i] * savings[year];
		carbonsYear[i] = mods[i] * carbonSavings[year];
	}
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
<html xmlns = "http://www.w3.org/1999/xhtml"> 

	<!-- Page header information. -->
	<head>
		<!--Page Title-->
		<title>Solar Calculator - Results</title>
		
		<!--Link to the formatting CSS document-->
		<link href="css/main.css" rel="stylesheet" type="text/css" />
		
		<!--Link to the rollover JavaScript code-->
		<script type="text/javascript" src="scripts/rollover.js"></script>
		
	    <style type="text/css">
			.style31 {color: #CC9900}
			.style32 {color: #FFFF82}
        .style33 {font-style: italic}
        </style>
</head>
	
	<!-- Page body information. -->
	<body onload="MM_PreloadNavigation();MM_preloadImages('images/navigationnew/ict-down.png')">
	
		<!-- Wrapper div, contains all of divs in the body -->
	<div class="wrapper"> 
			
				<!-- The heads for the page. -->
				<div class="header"><img src="images/banner.png" alt="Banner Image" width="744" height="95" /></div>
				
				<!-- Links for the page. -->
	  <div class="menu">
				<a href="home.html" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('HomeButton','','images/navigationnew/home-down.png',1)">
				<img src="images/navigationnew/home-up.png" alt="Home Button" name="HomeButton" width="152" height="30" border="0"  id="HomeButton" /></a>
				<a href="info.html" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('InfoButton','','images/navigationnew/info-down.png',1)">
				<img src="images/navigationnew/info-up.png" alt="Info Button" name="InfoButton" width="152" height="30" border="0"  id="InfoButton" /></a>
				<a href="calculator.html" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('FAQButton','','images/navigationnew/faq-down.png',1)">
				<img src="images/navigationnew/faq-up.png" alt="FAQ Button" name="FAQButton" width="152" height="30" border="0" id="FAQButton" /></a><br />	
	  </div>
		
	  <div class="content">
		  
		  		<div class="sidebox">
				<h1>Solar Power Calculator </h1>
				<p><span class="style31">Disclaimer</span><em>:</em> <em>All figures and results generated by the solar power calculator are <u>estimates only</u>. Actual results may vary based on incorrect input, location of installation, weather patterns in your area and many other factors. This calculator should be taken as a guide of expected power generation only, rather then a complete simulation.</em></p>
				<div align="left">
				  <p align="center" class="birthday"><span class="winners">Simple Summary</span> for Year 
  <% out.print(year + 1); %></p>
<table width="1017" border="0" cellpadding="3" cellspacing="7" class="tableborder">
                      <tr>
                        <td width="282" scope="col"><strong>Average Monthly Power Generation: </strong></td>
                        <td width="191" class="style32" scope="col"><% out.print(Math.round(power[year] / 12000.0) + "Kw"); %></td>
                        <td width="183" scope="col"><strong>Total Power Generation: </strong></td>
                        <td width="300" class="style32" scope="col"><% out.print(Math.round(power[year] / 1000) + "Kw"); %>.</td>
                      </tr>
                      <tr>
                        <td scope="col"><strong>Average Monthly Cost Savings: </strong></td>
                        <td class="style32" scope="col"><% out.print("$" + Math.round(savings[year] / 12.0)); %></td>
                        <td scope="col"><strong>Total Cost Savings: </strong></td>
                        <td class="style32" scope="col"><% out.print("$" + Math.round(savings[year])); %>.</td>
                      </tr>
                      <tr>
                        <td scope="col"><strong>Average Monthly Carbon Savings: </strong></td>
                        <td class="style32" scope="col"><% out.print(Math.round(carbonSavings[year] / 1200.0) / 10.0 + " tonnes"); %></td>
                        <td scope="col"><strong>Total Carbon Savings: </strong></td>
                        <td class="style32" scope="col"><% out.print(Math.round(carbonSavings[year] / 100.0) / 10.0 + " tonnes"); %>.</td>  
                      </tr>
                  </table>
                  </div>
                  <p>&nbsp;</p>
				</div>
				
				<div class="sidebox">
				<h1>Results Breakdown</h1>
				<p>Below is a list of year-by-year breakdowns of important information about the product. </p>
				<div align="center">
				  <table width="900" border="0" align="center" cellpadding="10" bgcolor="#000000" class="tableborder">
				  	<tr>
						<td><div align="center">
						  <p class="winners">Electricity Generation</p>
						  <p>Below is a power generation breakdown graph. </p>
						</div></td>
						<td><div align="center">
						  <p class="winners">Cost Savings</p>
						  <p>Below is a cost savings breakdown graph. </p>
						</div></td>
						<td><div align="center">
						  <p class="winners">Carbon Savings</p>
						  <p>Below is a carbon savings breakdown graph. </p>
						</div></td>
					</tr>
                    <tr>
                    	<td>
							<div align="center">
                        	<% 
								// Draw the power generation graph
								out.print("<img src=\"http://ebusiness.net78.net/monthoverview.php?data=");
								for (int i = 0; i < 12; i++) out.print(Math.round(powerYear[i] / 1000) + "*");
								out.print("\" />");
							%>
                      		</div>
					  	</td>
                      	<td>
							<div align="center">
					  		<% 
								// Draw the power generation graph
								out.print("<img src=\"http://ebusiness.net78.net/monthoverview.php?data=");
								for (int i = 0; i < 12; i++) out.print(Math.round(savingsYear[i]) + "*");
								out.print("\" />");
							%>
                      		</div>
					  	</td>
					  
					  	<td>
					  		<div align="center">
					  		<% 
								// Draw the power generation graph
								out.print("<img src=\"http://ebusiness.net78.net/monthoverview.php?data=");
								for (int i = 0; i < 12; i++) out.print(Math.round(carbonsYear[i] / 100.0) / 10.0 + "*");
								out.print("\" />");
							%>
					  		</div>
				 	  </td>	
				    </tr>
                  </table>
				</div>
				<p>&nbsp;</p>
				<div align="center">
					<p class="winners">Panel Breakdowns</p>
					<p>Below is a year by year breakdown of the panels and their outputs.  </p>
					<table align="center" cellpadding="10" class="tableborder" id="gradient-style">
					<thead>
					<tr>
						<th align="center"><strong>Year</strong></td>
						<th align="center"><strong>Power Generated</strong></td>
						<th align="center"><strong>Money Saved</strong></td>
						<th align="center"><strong>Carbon Saved</strong></td>
					</tr>
					</thead>
						<%
							// Write each of the rows for the table breakdown
							
						
							for (int i = 0; i < powerYear.length; i++) {
								out.print("<tr>");
									out.print("<td align=\"center\">" + "Year " + (i + 1) + "</td>");
									out.print("<td align=\"center\">" + Math.round(powerYear[i] / 1000) + "Kw" + "</td>");
									out.print("<td align=\"center\">" + "$" + Math.round(savingsYear[i]) + "</td>");
									out.print("<td align=\"center\">" + Math.round(carbonsYear[i] / 100.0) / 10.0 + " tonnes" + "</td>");
								out.print("</tr>");
							}
				
							// Write the totals at the end of the table
							out.print("<tr>");
							out.print("<td align=\"center\">" + "Total" + "</td>");
							out.print("<td align=\"center\">" + Math.round(power[year] / 1000) + "Kw" + "</td>");
							out.print("<td align=\"center\">" + "$" + Math.round(savings[year]) + "</td>");
							out.print("<td align=\"center\">" + Math.round(carbonSavings[year] / 100) / 10.0 + " tonnes" + "</td>");
							out.print("</tr>");
						%>
				  </table>
				</div>
	
				</div>
		        <p>&nbsp;</p>
	  </div>
	</div> 
</body>
</html>

